language: perl
perl:
    - "5.22"
    - "5.20"
    - "5.18"
matrix:
    fast_finish: true
before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov
  - bash <(curl -s https://codecov.io/bash)

install:
  - perl Build.PL
  - ./Build installdeps --cpan_client 'cpanm --quiet --notest'
